'''
sc-py-asdocs-vscode
Copyright 2025 Anggaranothing

This program is free software:
you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with this program.
If not, see <https://www.gnu.org/licenses/>.
'''
from pathlib import (
    Path as _Path,
)
from re import (
    sub as _resub,
    match as _rematch,
)
from datetime import (
    datetime as _dt,
    timezone as _tz,
)
from vdf import (
    VDFDict as _VDFDict,
    loads as _vdfloads,
    dumps as _vdfdumps,
)


AS_DOCS_VER = 2
ASP_DEFAULT = "default.as.predefined"
ASP_HEADER = '''/*
 * This file is auto-generated by https://github.com/anggaranothing/sc-py-asdocs-vscode
 * {2}
 *
 * Sven Co-op {0}
 * API version {1}
 */


'''
ASP_COMMENT_NEWLINE = "\n// "
ASP_FUNC_FORCE_REPLACEMENTS: dict[str,str] = {
    "NULL": "null",
    "Regex::ECMAScript": "Regex::FlagType::ECMAScript",
    "Regex::match_default": "Regex::MatchFlagType::match_default",
}
ASP_FUNC_IGNORED_ACCESSORS: list[str] = [
]


def fix_scientific_notation (value: str) -> str:
    pattern = r"(\d+?)e(\d+?)f" # e.g. 1e6f
    return _resub(pattern, r"\1e+\2f", value) # e.g. 1e+6f

def fix_comment_backslashes (value: str) -> str:
    return value \
        .replace("\t", " ") \
        .replace("\n", ASP_COMMENT_NEWLINE)

def fix_func_backslashes (value: str) -> str:
    return value \
        .replace("\t", "\\t") \
        .replace("\n", "\\n")

def fix_func_property_accessor (value: str) -> str:
    result = value
    pattern = r".+? ([gs]et_.+?)\(.*?\)" # e.g. "CModule@ get_g_Module()", "bool get_ShouldHide() const" & "void set_ShouldHide(bool fShouldHide)".
    matched = _rematch(pattern, value)
    if not matched:
        return result
    func_name = matched.groups()[0]
    if func_name in ASP_FUNC_IGNORED_ACCESSORS:
        return result
    # Add "property" suffix tag to mark it as a property accessor
    result = result + " property"
    return result

def fix_func_declaration (value: str) -> str:
    result = fix_func_property_accessor(
        fix_scientific_notation(
            fix_func_backslashes(value)
        )
    )
    for k,v in ASP_FUNC_FORCE_REPLACEMENTS.items():
        result = result.replace(k, v)
    return result

def get_namespace (vdf: _VDFDict) -> str:
    if "Namespace" in vdf:
        return vdf["Namespace"]
    return ""

def get_name (vdf: _VDFDict) -> str:
    if "Name" in vdf:
        return vdf["Name"]
    elif "Declaration" in vdf:
        return vdf["Declaration"]
    elif "InterfaceName" in vdf:
        return vdf["InterfaceName"]
    elif "ClassName" in vdf:
        return vdf["ClassName"]
    return ""

def get_link (link: str) -> str:
    return f"https://r4to0.github.io/asautodocs/docs/{link}.htm"

def write_comment (fp, vdf: _VDFDict, link=None):
    comment = ""
    ends_with_newline = False
    if "Documentation" in vdf and (comment := vdf["Documentation"]):
        comment = fix_comment_backslashes(comment)
        ends_with_newline = comment.endswith(ASP_COMMENT_NEWLINE)
        fp.write("// ")
        fp.write(comment)
        if not comment.endswith(".") and not ends_with_newline:
            fp.write(".")
        fp.write("\n")
    if link:
        link = str(link)
        if link == "typedef":
            link = "Typedefs"
        elif link == "funcdef":
            link = "FuncDefs"
        elif link == "func":
            link = "Functions"
        elif link == "prop":
            link = "Properties"
        if comment and not ends_with_newline:
            fp.write("//")
            fp.write("\n")
        fp.write(f"// @link {get_link(link)}")
        fp.write("\n")

class Block:
    def __init__ (self, fp, prefix: str|None=None):
        self._fp = fp
        self._prefix = prefix

    def __enter__ (self):
        self._fp.write(f"{self._prefix} {{")
        self._fp.write("\n")

    def __exit__ (self, exc_type, exc_value, traceback):
        self._fp.write("}")
        self._fp.write("\n")

class DescriptiveBlock (Block):
    def __init__ (self, fp, vdf: _VDFDict):
        super().__init__(fp, get_name(vdf))
        self._vdf = vdf

    def __enter__ (self):
        write_comment(self._fp, self._vdf, get_name(self._vdf))
        super().__enter__()

class Namespace (Block):
    def __init__ (self, fp, vdf: _VDFDict):
        super().__init__(fp)
        self._namespaces = get_namespace(vdf).split("::")
        if not self._namespaces[0]:
            del self._namespaces[0]

    def __enter__ (self):
        for x in self._namespaces:
            self._prefix = f"namespace {x}"
            super().__enter__()
        self._prefix = None

    def __exit__ (self, exc_type, exc_value, traceback):
        for _ in self._namespaces:
            super().__exit__(exc_type, exc_value, traceback)

def _write_basic (fp, vdf: _VDFDict, datatype: str, txt: str, parent: tuple[str,_VDFDict]|None=None):
    namespace = get_namespace(vdf) or "<Global>"
    name = get_name(vdf)
    param2 = datatype.upper()
    param3 = ""
    if parent:
        param3 = f"[{param2}]"
        datatype = get_name(parent[1])
        param2 = f"{parent[0].upper()} {datatype}"
    yield f'[{namespace}][{param2}]{param3} Writing "{name}"...'
    with Namespace(fp, vdf):
        write_comment(fp, vdf, datatype)
        fp.write(txt)
        fp.write("\n")
    if not parent:
        fp.write("\n")

def iter_write_typedef (fp, vdf: _VDFDict):
    return _write_basic(fp, vdf, "typedef", f"typedef {vdf["Type"]} {get_name(vdf)};")

def iter_write_funcdef (fp, vdf: _VDFDict):
    return _write_basic(fp, vdf, "funcdef", f"funcdef {fix_func_declaration(get_name(vdf))};")

def iter_write_property (fp, vdf: _VDFDict, parent: tuple[str,_VDFDict]|None=None):
    return _write_basic(fp, vdf, "prop", f"{get_name(vdf)};", parent)

def iter_write_function (fp, vdf: _VDFDict, parent: tuple[str,_VDFDict]|None=None):
    return _write_basic(fp, vdf, "func", f"{fix_func_declaration(get_name(vdf))};", parent)

class Enum (DescriptiveBlock):
    def __init__ (self, fp, vdf: _VDFDict):
        super().__init__(fp, vdf)
        self._prefix = f"enum {get_name(self._vdf)}"

def _write_enum_value (fp, vdf: _VDFDict, parent: _VDFDict):
    namespace = get_namespace(vdf) or "<Global>"
    parent_name = get_name(parent)
    name = get_name(vdf)
    value = vdf["Value"]
    yield f'[{namespace}][ENUM {parent_name}] Writing "{name}"...'
    try:
        value = int(value)
    except ValueError:
        try:
            value = float(value)
        except ValueError:
            value = f'"{value}"'
    write_comment(fp, vdf, parent_name)
    fp.write(f"{name} = {value},")
    fp.write("\n")

def iter_write_enum (fp, vdf: _VDFDict):
    namespace = get_namespace(vdf) or "<Global>"
    name = get_name(vdf)
    yield f'[{namespace}][ENUM] Writing "{name}"...'
    with Namespace(fp, vdf):
        with Enum(fp, vdf):
            for v in reversed([*vdf["Values"].itervalues()]):
                yield from _write_enum_value(fp, v, vdf)
    fp.write("\n")

class Interface (DescriptiveBlock):
    def __init__ (self, fp, vdf: _VDFDict):
        super().__init__(fp, vdf)
        self._prefix = f"interface {get_name(self._vdf)}"

def iter_write_interface (fp, vdf: _VDFDict):
    namespace = get_namespace(vdf) or "<Global>"
    name = get_name(vdf)
    yield f'[{namespace}][INTERFACE] Writing "{name}"...'
    with Namespace(fp, vdf):
        with Interface(fp, vdf):
            for v in reversed([*vdf["Methods"].itervalues()]):
                yield from iter_write_function(fp, v, ("interface", vdf))
    fp.write("\n")

class Class (DescriptiveBlock):
    def __init__ (self, fp, vdf: _VDFDict):
        super().__init__(fp, vdf)
        self._prefix = f"class {get_name(self._vdf)}"

def fix_class_constructor (vdf: _VDFDict, parent: _VDFDict) -> str:
    result = get_name(vdf)
    parent_name = get_name(parent)
    pattern = r"(.+?) (.+?)(\(.*?\))" # e.g. "void string()", "Arguments@ Arguments(const Arguments& in other)".
    matched = _rematch(pattern, result)
    if not matched:
        return result
    func_name = matched.groups()[1]
    if func_name != parent_name:
        return result
    # Delete return datatype, straight into func name and its arguments.
    result = _resub(pattern, r"\2\3", result)
    return result

def iter_write_class (fp, vdf: _VDFDict):
    namespace = get_namespace(vdf) or "<Global>"
    name = get_name(vdf)
    yield f'[{namespace}][CLASS] Writing "{name}"...'
    with Namespace(fp, vdf):
        with Class(fp, vdf):
            for v in reversed([*vdf["Properties"].itervalues()]):
                yield from iter_write_property(fp, v, ("class", vdf))
            for v in reversed([*vdf["Methods"].itervalues()]):
                v[0, "Declaration"] = fix_class_constructor(v, vdf)
                yield from iter_write_function(fp, v, ("class", vdf))
    fp.write("\n")

def iter_build (vdf: _VDFDict, outpath: _Path):
    if not isinstance(vdf, _VDFDict):
        raise TypeError("Invalid VDF instance")

    if "Angelscript Documentation" not in vdf or not isinstance(vdf := vdf["Angelscript Documentation"], _VDFDict):
        raise ValueError("Node \"Angelscript Documentation\" must be a block node")

    if "DocVersion" not in vdf:
        raise ValueError("Document version key missing. Old Format?")
    docver = int(vdf["DocVersion"])
    if docver != AS_DOCS_VER:
        raise ValueError(f"Invalid document version (found {docver}, expected {AS_DOCS_VER})")
    yield f"Document version: {docver}"

    if "GameVersion" not in vdf:
        raise ValueError("Game version key missing. Old Format?")
    gamever = vdf["GameVersion"]
    yield f"Game version: {gamever}"

    gamebuild = None
    if "GameBuild" in vdf:
        gamebuild = vdf["GameBuild"]
    yield f"Internal Build: {gamebuild}"

    apiver = vdf["APIVersion"]

    with outpath.open("w") as fp:
        param1 = gamever
        if gamebuild:
            param1 = param1 + f" (Internal build {gamebuild})"
        param3 = _dt.now(_tz.utc).replace(tzinfo=None).isoformat(" ")
        yield "Writing header..."
        fp.write(ASP_HEADER.format(param1, apiver, param3))
        yield "Writing default syntaxes..."
        with _Path(ASP_DEFAULT).open("r") as tempfp:
            fp.writelines(tempfp.readlines())
            fp.write("\n\n")
        # Writes off
        kf = {
            "Typedefs": iter_write_typedef,
            "Enums": iter_write_enum,
            "FuncDefs": iter_write_funcdef,
            "Interfaces": iter_write_interface,
            "Classes": iter_write_class,
            "Properties": iter_write_property,
            "Functions": iter_write_function,
        }
        for k, func in kf.items():
            for item in reversed([*vdf[k].itervalues()]):
                yield from func(fp, item)

def asdocs2vdf (filepath) -> _VDFDict|None:
    filepath = _Path(filepath)
    # Load asdocs into memory
    vdf = filepath.read_text()
    # Fix namespaces
    vdf = _resub(r'Namespace ([^"].+)', r'Namespace "\1"', vdf)
    # Fix single-char enum values
    vdf = _resub(r"Value \\'(\S)\\'", r'Value "\1"', vdf)
    # Parse as VDF
    vdf = _vdfloads(vdf, merge_duplicate_keys=False, mapper=_VDFDict)
    # Writes off
    outpath = filepath.with_suffix(".vdf")
    with outpath.open("w") as ofp:
        ofp.write(_vdfdumps(vdf, pretty=True))
    return vdf

def main (filepath, outpath):
    filepath = _Path(filepath).resolve(True)
    print(f'Input file: "{filepath}"')
    outpath = _Path(outpath).resolve(False)
    print(f'Output file: "{outpath}"')
    vdf = asdocs2vdf(filepath)
    for msg in iter_build(vdf, outpath):
        print(msg)
    print("Finished!")
    #debug(vdf["Angelscript Documentation"])

def debug (vdf: _VDFDict):
    for k,v in vdf.iteritems():
        if not isinstance(v, str):
            if vv := v.get_all_for(k):
                v = vv
            else:
                v = f"[{len(v)}]"
        print(k, v)

if __name__ == "__main__":
    import sys
    main(
        sys.argv[1] if len(sys.argv) > 1 else "asdocs.txt",
        sys.argv[2] if len(sys.argv) > 2 else "as.predefined",
    )
